### PR TITLE
fix connection not getting closed

### LINKED ISSUE #110: 执行后不自动 结束  mongodb
mgDF = sqlContext.read.format("com.stratio.datasource.mongodb").options(
        credentials="xxxxxxxxx",
        collection="xxxxx",
        host="xxxxxxx",
        database="xxxxxxx").load()
    mgDF.registerTempTable("mgDF")

执行后  任务不结束 数据 已经打印完了 不自动 结束

### PR DESCRIPTION
**Pull request by wuciawe**
It fixes #110, and it may be related with #109 .

### CODE REVIEW

**Comment by pfcoperez** [comment]
@wuciawe  Thanks! That's exactly the solution. Could you please squash your changes so only one commit will contain them?

File: spark-mongodb/src/main/scala/com/stratio/datasource/mongodb/client/MongodbClientFactory.scala [hunk 1]
```diff
@@ -43,7 +44,12 @@ object MongodbClientFactory {
   /**
    * Scheduler that close connections automatically when the timeout was expired
    */
-  private val actorSystem = ActorSystem()
+  private val actorSystem = ActorSystem("mongodbClientFactory", ConfigFactory.load(ConfigFactory.parseString(
+    """
```
Comment (pfcoperez) [inline spark-mongodb/src/main/scala/com/stratio/datasource/mongodb/client/MongodbClientFactory.scala]: I think, the more concise, notation `ConfigFactory.parseString("akka.daemonic=on")` would fit better in this case.

**Comment by wuciawe** [comment]
@pfcoperez I squashed them into one commit and took your notation.
