### PR TITLE
fix reading properties without changing old configuration

### LINKED ISSUE #111: Cannot supply samplingRatio when creating a DataFrame
Thanks very much for the spark-mongodb connector, much appreciated.

I'm having an issue when creating a DataFrame from a MongoDB collection. 

The elapsed time for creating the DataFrame is 2 -3 seconds, in this scenario:

* I am connecting to a remote MongoDB cluster
* I am creating the DataFrame from a collection with 250 small documents (average document size is 71 bytes)
* I am not supplying a schema, so I am expecting Stratio's MongoDB's ``DefaultSource`` to infer the schema
* I am supplying a sample ratio to (I think!) limit the amount of data which must be read in order to infer the schema

Walking the code I can see that:

* DataFrameReader.load() creates a ``org.apache.spark.sql.execution.datasources.ResolvedDataSource``, which - in ``case RelationProvider`` - creates a CaseInsensitiveMap from the given options and then invokes ``com.stratio.datasource.mongodb.DefaultSource``
* The ``DefaultSource`` creates a ``new MongodbRelation`` but provides *no* schema which (see ``MongodbRelation:58``) results in the use of a lazy schema like so:

```
MongodbSchema(new MongodbRDD(sqlContext, config, rddPartitioner), config.get[Any](MongodbConfig.SamplingRatio).fold(MongodbConfig.DefaultSamplingRatio)(_.toString.toDouble)).schema()  
```

* The key item here is this: ``'config.get[Any](MongodbConfig.SamplingRatio).fold(MongodbConfig.DefaultSamplingRatio)'`` which uses or overrides the caller supplied samplingRatio expecting the sampling ratio to be provided under the key "schema_samplingRatio" but because the ``ResolvedDataSource``has already case insensitised the caller supplied properties our sampling ratio is actually under the key "schema_samplingratio" so the provided MongodbSchema always uses the default sample ratio: 1.0
		
Am I correct in the above diagnosis? If so, what can be done about it? If not, how can I realiably provide my own sampling ratio?

Version details etc:

* org.scala-lang::scala-library::2.11.6
* com.stratio.datasource::spark-mongodb_2.11::0.11.1
* com.stratio::spark-mongodb::0.8.7
* org.apache.spark::spark-sql_2.11::1.6.1 

Here's a test case showing the behaviour in action;

```
  @Test
  public void canReproduceCallerSuppliedSamplingRatioIssue() {
    SparkConf sparkConf = new SparkConf()
        .setAppName("ProvidingASamplingRatio")
        .setMaster("local[*]");

    JavaSparkContext sc = new JavaSparkContext(sparkConf);

    SQLContext sqlContext = new SQLContext(sc);

    Double samplingRatio = 0.1;
    long start = System.currentTimeMillis();
    DataFrame countriesSlow = sqlContext
        .read()
        .format("com.stratio.datasource.mongodb")
        .options(getOptions("Scratch", "countries", samplingRatio))
        .load();
    // the preceding call takes 2 - 3 *seconds*
    System.out.println(String.format("Loaded countries without a schema in: %sms using caller supplied sampling ratio: %s",
        (System.currentTimeMillis() - start), samplingRatio));
    countriesSlow.show(5);

    StructType countriesSchema = DataTypes.createStructType(Arrays.asList(
        DataTypes.createStructField("code", DataTypes.StringType, true),
        DataTypes.createStructField("region", DataTypes.StringType, true),
        DataTypes.createStructField("name", DataTypes.StringType, true)
    ));

    start = System.currentTimeMillis();
    DataFrame countriesFast = sqlContext
        .read()
        .format("com.stratio.datasource.mongodb")
        .options(getOptions("Scratch", "countries", null))
        .schema(countriesSchema)
        .load();
    // the preceding call takes 2 - 3 *millis*
    System.out.println(String.format("Loaded countries with a schema in: %sms using default sampling ratio",
        (System.currentTimeMillis() - start)));
    countriesFast.show(5);
  }

  private static Map getOptions(String databaseName, String collectionName, Double samplingRatio) {
    Map options = new HashMap();
    // see MongodbConfig
    options.put("host", "...");
    options.put("credentials", "...");
    options.put("database", databaseName);
    options.put("collection", collectionName);
    if (samplingRatio != null) {
      options.put("schema_samplingRatio", samplingRatio);
    }
    return options;
  }
```

### PR DESCRIPTION
**Pull request by wuciawe**
it fixes #111, and unlike #112, it doesn't require to change old configuration, it's implemented inspired by the org.apache.spark.sql.execution.datasources.CaseInsensitiveMap in SPARK-SQL.

### CODE REVIEW

**Comment by pfcoperez** [comment]
@wuciawe We'll follow your approach since, as you well pointed out, would keep backward compatibility.
Thanks again for another good contribution.

File: spark-mongodb/src/main/scala/com/stratio/datasource/mongodb/partitioner/MongodbPartitioner.scala [hunk 1]
```diff
@@ -45,7 +45,10 @@ class MongodbPartitioner(config: Config) extends Partitioner[MongodbPartition] {
   @transient private val ssloptions: Option[MongodbSSLOptions] =
     config.get[MongodbSSLOptions](MongodbConfig.SSLOptions)
 
-  private val clientOptions = config.properties //config.properties.filterKeys(_.contains(MongodbConfig.ListMongoClientOptions)) // TODO review this Map. Can't filter keys
+  private val clientOptions = {
+    val lowerCaseOptions = MongodbConfig.ListMongoClientOptions.map(_.toLowerCase)
+    config.properties.filter(kv => kv._1.contains(lowerCaseOptions))
```
Comment (pfcoperez) [inline spark-mongodb/src/main/scala/com/stratio/datasource/mongodb/partitioner/MongodbPartitioner.scala]: The logic here is wrong: You are filtering those `config` properties which does not contain the whole option list.

I'd try something like:

```
lowerCaseOptions.filter(config.properties.contains(_))
```

File: spark-mongodb/src/main/scala/com/stratio/datasource/util/Config.scala [hunk 2]
```diff
@@ -62,7 +62,7 @@ abstract class ConfigBuilder[Builder<:ConfigBuilder[Builder] ](
    */
   def build(): Config = new Config {
 
-    val properties = builder.properties
+    val properties = builder.properties.map(kv => kv.copy(_1 = kv._1.toLowerCase))
```
Comment (pfcoperez) [inline spark-mongodb/src/main/scala/com/stratio/datasource/util/Config.scala]: This approach is more readable:

`val properties = builder.properties.map { case (k, v) => k.toLowerCase -> v }`

**Comment by pfcoperez** [comment]
@wuciawe Change as suggested, before committing make sure you pass the project test set, we'll pass them for a second time and if everything is OK we'll merge

File: spark-mongodb/src/main/scala/com/stratio/datasource/mongodb/partitioner/MongodbPartitioner.scala (hunk 1 above)
Comment (pfcoperez) [inline spark-mongodb/src/main/scala/com/stratio/datasource/mongodb/partitioner/MongodbPartitioner.scala]: Looking at your commits I see you had already noticed that `filterKeys` isn't compatible with a map to be distributed to Spark workers as its return instance is not serializable. In any case, you should apply the logic I proposed:

```
 private val clientOptions = {
   val lowerCaseOptions = MongodbConfig.ListMongoClientOptions.map(_.toLowerCase).toSet
   config.properties.filter { case (k, _) => lowerCaseOptions contains k }
 }
```

**Comment by wuciawe** [comment]
@pfcoperez I merged your suggestion and project tests all pass on local machine. Sorry for wrong logic produced in previous pull request, I'm surprised that the wrong code compiles. Is it necessary to squash all those commits into one this time?

**Comment by pfcoperez** [comment]
@wuciawe No worries. I was surprised too, probably a consequence `WrappedString#CanBuildFrom`.
You don't need to squash I'll do it using new GitHub merge tool.

Thanks again.
